### ISSUE TITLE
Adicionar linter ao projeto

### ISSUE THREAD

**Issue by DevRadhy** [aHub-Tech/hub-discord#12]
## O que será feito?
Será adicionado o `ESLint` para padronizar o desenvolvimento do código.

**Comment by vcwild** [comment]
Bom dia @DevRadhy , você acha interessante fazermos uma action de CI com o ESLint?

**Comment by DevRadhy** [comment]
> Bom dia @DevRadhy , você acha interessante fazermos uma action de CI com o ESLint?

além do ESLint no código do desenvolvedor, ter uma action eu acho interessante sim 😀
